data_source: CDS
graphql_url: https://dataservice.datacommons.cancer.gov/v1/graphql/
file_keyword: file
file_identifier: file.file_id
source_file_identifier: file_id
diagnosis_keyword: diagnosis
diagnosis_identifier: diagnosis.diagnosis_id
source_diagnosis_identifier: diagnosis_id
treatment_keyword: treatment
treatment_identifier: treatment.treatment_id
source_treatment_identifier: treatment_id
specimen_query_keyword: sample
specimen_map_keyword: specimen
specimen_identifier: specimen.specimen_id
source_specimen_identifier: sample_id
subject_keyword: participant
subject_identifier: subject.subject_id
source_subject_identifier: subject_identifier
research_subject_keyword: participant
research_subject_identifier: subject.subject_id
source_research_subject_identifier: subject_id
query_module: cdsQueries
field_mapping_file: CDA-CDS_mapping.yaml
json_schema: cda_metadata_submission.schema.json
